easy_admin:
    entities:
#        # List the entity class name you want to manage
        - App\Entity\Player
        - App\Entity\Team
        - App\Entity\Game
#        - App\Entity\Category
#        - App\Entity\User
